# Generated by Django 5.0.1 on 2024-01-24 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_question_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
