# Generated by Django 5.0.2 on 2024-03-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
