# Generated by Django 5.0.2 on 2024-03-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_group',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
