# Generated by Django 5.0.2 on 2024-03-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_task_task_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
